branches:
  only:
    - master
    - /^v.*$/

language: node_js

env:
  NO_PREBUILD=true

git:
  depth: false
  quiet: true

# https://pnpm.io/continuous-integration#travis
cache:
  npm: false
  directories:
    - "~/.pnpm-store"

# Travis 的 jobs 只继承外层的第一个环境，目前只想到用引用的方式来生成任务
_job_win: &job_windows
  os: windows
  before_install: choco install python

# Node 16 要求 Python >= 3.6，Xenial 没有要用最新版系统。
_job_linux: &job_linux
  os: linux
  dist: focal

jobs:
  include:
    - <<: *job_windows
      node_js: 17

    - <<: *job_linux
      node_js: 17

install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
  - pnpm install -g node-gyp
  - pnpm install --no-optional

before_script: node-gyp rebuild

script: pnpm test

after_success: node script/prebuild.js pack

deploy:
  provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file_glob: true
  file: prebuilds/*
  on:
    tags: true
