branches:
  only:
    - master
    - /^v.*$/

language: node_js

git:
  depth: false
  quiet: true

# Travis 的 jobs 只继承外层的第一个环境，目前只想到用引用的方式来生成任务
job_win: &job_windows
  os: windows
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  before_install:
    - choco install python
    - npm install -g node-gyp

job_linux: &job_linux
  os: linux
  before_install: npm install -g node-gyp

jobs:
  include:
    - <<: *job_windows
      node_js: 14
      before_install: npm i -g npm@next-7

    - <<: *job_windows
      node_js: 15

    - <<: *job_linux
      node_js: 14
      before_install: npm i -g npm@next-7

    - <<: *job_linux
      node_js: 15

install: npm ci --no-prebuild --no-optional

before_script: node-gyp rebuild

after_success: node script/prebuild.js pack

deploy:
  provider: releases
  cleanup: false
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: prebuilds/*
  on:
    tags: true
