branches:
  only:
    - master
    - /^v.*$/

language: node_js
node_js: 14

git:
  depth: false
  quiet: true

jobs:
  include:
    - os: windows
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python
        - npm install -g node-gyp
      install: npm ci --build-from-source

    - os: linux
      before_install: npm install -g node-gyp
      install: npm ci --build-from-source

deploy:
  provider: script
  script: npm run upload-ci
  on:
    tags: true
