if: branch = master

language: node_js
node_js: 14

git:
  depth: false
  quiet: true

jobs:
  include:
    - os: windows
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python
        - npm install -g node-gyp
      install: npm install --build-from-source
      script: npm run test

    - os: linux
      addons:
        apt:
          update: true
          packages:
            - build-essential

      before_install:
        - npm install -g node-gyp
      install: npm install --build-from-source
      script: npm run test

deploy:
  provider: script
  script: npm run upload-ci
  on:
    tags: true
