name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: actions/checkout@v4

      - name: Cache .pnpm-store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Node deps
        run: |
          npm i -g pnpm node-gyp
          pnpm install
        env:
          NO_PREBUILD: true

      - run: node-gyp rebuild

      - run: pnpm run test:coverage

      - uses: codecov/codecov-action@v4
